# Generated by Django 5.1.6 on 2025-03-09 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_of_the_letter', models.CharField(blank=True, max_length=100, null=True, verbose_name='subject of the letter')),
                ('letter_body', models.TextField(blank=True, null=True, verbose_name='letter body')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='full Name')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('end_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='date and time ending')),
                ('status', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('started', 'Запущена')], max_length=10, verbose_name='status')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='message')),
                ('recipients', models.ManyToManyField(to='mailing.recipient', verbose_name='recipients')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'ordering': ['message', 'owner'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Не успешно')], max_length=20, verbose_name='status')),
                ('response', models.TextField(verbose_name='response')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.message', verbose_name='message')),
            ],
            options={
                'verbose_name': 'Attempt Mailing',
                'verbose_name_plural': 'Attempts Mailings',
            },
        ),
    ]
