# Generated by Django 5.1.6 on 2025-03-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trymailing',
            name='message',
        ),
        migrations.AddField(
            model_name='trymailing',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.mailing', verbose_name='mailing'),
            preserve_default=False,
        ),
    ]
