# Generated by Django 5.1.6 on 2025-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_trymailing_message_trymailing_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AlterField(
            model_name='trymailing',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='response'),
        ),
    ]
