# Generated by Django 5.1.6 on 2025-03-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_last_sent_alter_trymailing_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='last_sent',
        ),
    ]
