# Generated by Django 5.1.6 on 2025-03-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailing_last_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки'),
        ),
    ]
