# Generated by Django 5.1.6 on 2025-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailing_last_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trymailing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
