# Generated by Django 5.1.6 on 2025-03-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_trymailing_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['message', 'owner'], 'permissions': [('can_view_all_mailings', 'Может просматривать все рассылки'), ('can_disable_mailing', 'Может отключать рассылки')], 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_view_all_messages', 'Может просматривать все сообщения')], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_view_all_recipients', 'Может просматривать всех получателей')], 'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
    ]
